### ISSUE TITLE
Typo in the file

### ISSUE THREAD

**Issue by rohanbabbar04** [opencodeiiita/PanoViewer#15]
![image](https://user-images.githubusercontent.com/77425744/135872794-1f4c960a-f042-4ae8-93e7-dfbdd6a61f83.png)

Typo in the above image

**Comment by Ms-Error** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
Okay so there are multiple instances of Sensitivity being written as Senstivity, so you need to refactor all the fields and methods with that name in the project. Also correct similar mistyped comments if you find any.

**Comment by GhostFoxSledgehammer** [comment]
**Before** claiming this issue you need to complete issue #9.

**Comment by rohanbabbar04** [comment]
OK I have done it will send a screen shot here

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> OK I have done it will send a screen shot here

Send your ss in issue 9's thread.

**Comment by rohanbabbar04** [comment]
> > OK I have done it will send a screen shot here
> 
> Send your ss in issue 9's thread.

Done

**Comment by rohanbabbar04** [comment]
> Okay so there are multiple instances of Sensitivity being written as Senstivity, so you need to refactor all the fields and methods with that name in the project. Also correct similar mistyped comments if you find any.

Okay

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
Assigned to @rohanbabbar04 .
Please submit your PR by 7th Oct 8:31Am

**Comment by GhostFoxSledgehammer** [comment]
Fixed in #20
