### ISSUE TITLE
Create method to check if Image ratio is 2:1.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#23]
You need to create a method which return true when the image width to height ratio is  2:1, false otherwise.
It should take a `bufferedImage` as parameter.
Method should be in `imageutils` class.
Also make `imageutils` class constructor private.

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> Claim

Assigned to @isharawat

**Comment by bipulkmr-crypto** [comment]
is this issue open for claim @GhostFoxSledgehammer ?
