### ISSUE TITLE
Need a logo for PanoViever

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#3]
You need to make a logo which is close to what the project actually does.
You need to put the logo in `src/main/resources/Images/` folder with name as `logo`
**This issue is open for all and needs not be claimed**.

Example:- 

- [This](https://www.google.com/imgres?imgurl=https%3A%2F%2Fc8.alamy.com%2Fcomp%2FP2DM47%2F360-panorama-vector-icon-isolated-on-transparent-background-360-panorama-logo-concept-P2DM47.jpg&imgrefurl=https%3A%2F%2Fwww.alamy.com%2F360-panorama-vector-icon-isolated-on-transparent-background-360-panorama-logo-concept-image208054903.html&tbnid=eBCSWirYjw9OnM&vet=12ahUKEwiut7nG-6_zAhUZsksFHRP-DAAQMygqegUIARCTAg..i&docid=bGjPhxcO12dihM&w=1300&h=1390&q=panorama%20logo&client=firefox-b-d&ved=2ahUKEwiut7nG-6_zAhUZsksFHRP-DAAQMygqegUIARCTAg)
- [This](https://www.google.com/imgres?imgurl=https%3A%2F%2Fthumbs.dreamstime.com%2Fz%2Fpanorama-icon-vector-sign-symbol-isolated-white-backgroun-background-your-web-mobile-app-design-logo-concept-133737508.jpg&imgrefurl=https%3A%2F%2Fwww.dreamstime.com%2Fpanorama-icon-vector-sign-symbol-isolated-white-backgroun-background-your-web-mobile-app-design-logo-concept-image133737508&tbnid=lkNR-LGp8ZyGjM&vet=12ahUKEwiut7nG-6_zAhUZsksFHRP-DAAQMygtegUIARCaAg..i&docid=pdxEcb__-rel5M&w=1600&h=1689&q=panorama%20logo&client=firefox-b-d&ved=2ahUKEwiut7nG-6_zAhUZsksFHRP-DAAQMygtegUIARCaAg)

**Comment by janhaviiii** [comment]
claim

**Comment by Tanushree-coder** [comment]
please assign this issue to me

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
**This issue is open for all and needs not be claimed.**

**Comment by Pranav-22-aditya** [comment]
claim

**Comment by shlesh** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
In case the instructions were unclear, you need to **create** a new logo. Avoid plagiarism and do not use stock images without permissive licenses.
