### ISSUE TITLE
Create shortcut and action for Opening menu item

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#30]
You need to add shortcut to `Open` menu item present in `Menu` class(ctrl + f probably).
Also create a static method in `IOUtils` class called `chooseFile` with no arguments. Leave the method body blank.
Add a actionlistener to the `Open` menu item which calls this static method.
Write meaning comments wherever you feel the need to.
Make all the changes to the `dev` branch.

**Comment by jalanprakhar** [comment]
claim
