### ISSUE TITLE
Implement opening of file and setting images.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#38]
You need to complete the `choosefile` method present in IOUtils class. It should display a file chooser(present in default package) and then get the selected image, and if it is valid it should set the image in SwitchModes class instance(currently it does not have a field to store images, so create one and a method to set the image).
All changes should be in `dev` branch.

**Comment by Tanushree-coder** [comment]
> Here are some resources you may need :-
> 
> * JFileChooser
>   [JavaDoc](https://docs.oracle.com/javase/7/docs/api/javax/swing/JFileChooser.html)
> * ImageIO
>   [StackOverFlow](https://stackoverflow.com/questions/19447104/load-image-from-a-filepath-via-bufferedimage)
> 
> So basically you need to first change the `choosefile` method to display a filechooser. You don't need to create a new `JFileChooser`, you can get it's instance from `FIlePicker` class by calling it's `getInstance()` method. After the user selects the file you need to open that file using ImageIO(with proper exception handling) which will return a `bufferedimage`. If the `bufferedimage` is valid then just pass this bufferedimage to Switch Mode class instance.
> 
> If you are confused by what I mean by instance, you should read this [Singleton in java](https://www.baeldung.com/java-singleton)

Sir, I'm getting this error, can you please tell where am I going wrong?

![image](https://user-images.githubusercontent.com/75807670/136693876-d9275bab-ad91-413e-9de3-0aba80bbfeab.png)
