### ISSUE TITLE
Add a menu projection mode.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#39]
In the menu bar class, create a menu item for selecting mode which should have 2 modes :- pano and flat.
You need to add action to these menu items so when they are clicked there corresponding modes are opened in  SwitchMode class. See imagepanel class for enums for the 2 modes.

All changes should be made in ~~`dev`~~ `master` branch.

**Comment by Puja-Saraf** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
Resources
- JMenuBar
	[JavaDoc](https://docs.oracle.com/javase/7/docs/api/javax/swing/JMenuBar.html)
	[Video tutorial](https://www.youtube.com/watch?v=TGl17kj7vwQ)
	[Mutually Exclusive menu items](https://www.infoworld.com/article/2077529/java-tip-31--how-to-create-mutually-exclusive-menus-in-java.html)

Your menu items should be mutually exclusive, so only a single mode is active at a time(pano mode by default).
According to the selected mode, you need to call the setCurrentMode() function present int `SwichModes` class with the corresponding enums as arguments.
Take a look at ImagePanels class for enums, and SwitchModes class for how the both modes are set.

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by AgrimVerma** [comment]
> 
> 
> claim and i have also claimed at yesterday night when the deadline was close

But we have to claim when its open to claim, that's the whole point.

**Comment by GhostFoxSledgehammer** [comment]
You need to make changes in `master` branch now.

**Comment by rohanbabbar04** [comment]
Claim
