### ISSUE TITLE
Create Action for exiting app.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#41]
Add action for exiting from the app when clicking the exit menu item in menubar.
Make all changes in `dev` branch

**Comment by jalanprakhar** [comment]
ckaim

**Comment by Puja-Saraf** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> claim

You already have 4 issue assigned to you.

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> > You already have 4 issue assigned to you.
> 
> sir I have 3 assigned

As per my info You have a issue assigned in each of these repos

- Ask-Us-Frontend
- Numismatics
- Contest-Countdown
- Collaborative-App

If there is any inconsistency then let me know.

**Comment by Puja-Saraf** [comment]
> > > You already have 4 issue assigned to you.
> > 
> > 
> > sir I have 3 assigned
> 
> As per my info You have a issue assigned in each of these repos
> 
> * Ask-Us-Frontend
> * Numismatics
> * Contest-Countdown
> * Collaborative-App
> 
> If there is any inconsistency then let me know.

Sir Collaborative-App issue is closed and pr was merged in the afternoon

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> > > > You already have 4 issue assigned to you.
> > > 
> > > 
> > > sir I have 3 assigned
> > 
> > 
> > As per my info You have a issue assigned in each of these repos
> > 
> > * Ask-Us-Frontend
> > * Numismatics
> > * Contest-Countdown
> > * Collaborative-App
> > 
> > If there is any inconsistency then let me know.
> 
> Sir Collaborative-App issue is closed and pr was merged in the afternoon

Yeah its a error from there side, will you claim another issue of same difficulty in this repo?

**Comment by Puja-Saraf** [comment]
> > > > > > > You already have 4 issue assigned to you.
> > > > > > 
> > > > > > 
> > > > > > sir I have 3 assigned
> > > > > 
> > > > > 
> > > > > As per my info You have a issue assigned in each of these repos
> > > > > 
> > > > > * Ask-Us-Frontend
> > > > > * Numismatics
> > > > > * Contest-Countdown
> > > > > * Collaborative-App
> > > > > 
> > > > > If there is any inconsistency then let me know.
> > > > 
> > > > 
> > > > Sir Collaborative-App issue is closed and pr was merged in the afternoon
> > > 
> > > 
> > > Yeah its a error from there side, will you claim another issue of same difficulty in this repo?
> > 
> > 
> > do I need to claim it or you'll directly assign it to me?
> 
> I'll assign it only if you tell me here.

yes sir
