### ISSUE TITLE
Create a about dialog.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#5]
Create a class named `AboutDialog` which extends ~~`JDialog`~~ `JPanel`.
Show some description of the project. Also add a link to this repo in the form of hyperlink inside a `JLabel` or a button which opens browser.
File should be in `gui` package.
 See example for About dialogs :-
 
![image](https://user-images.githubusercontent.com/54080100/135800866-c22efee4-440d-42ed-8e10-eebda4a500e5.png)
![image](https://user-images.githubusercontent.com/54080100/135800905-051ec704-208b-45d9-8b90-56ad0084f353.png)
![image](https://user-images.githubusercontent.com/54080100/135800963-e00f6882-68b1-4b53-bc31-dceea7bd29e5.png)
![image](https://user-images.githubusercontent.com/54080100/135801017-5ba49b9d-c839-4e7d-94be-5e6fb6d6f9fb.png)

**Comment by Ayushi181** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> claim

Assigned to @Ayushi181 
Please submit your PR by 6th Oct 11:27 AM.

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> > claim
> 
> Assigned to @Ayushi181 Please submit your PR by 6th Oct 11:27 AM.

Unassinged

**Comment by GhostFoxSledgehammer** [comment]
Assigned to @bipulkmr-crypto 
Submit your PR by 8th Oct 12:39 PM

**Comment by GhostFoxSledgehammer** [comment]
Fixed in #35
