### ISSUE TITLE
Set imagepanel based on Image ratio.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#53]
Complete the setImage method in SwitchModes class. It should cache the Image provided as argument and set the current mode of Image based on the ratio of image.
There is already a method present in imageutils to check what the image ratio is. If image is 2:1 then set the mode as pano otherwise as flat mode.
Also make the SwitchingModes method private.

**Comment by Tanushree-coder** [comment]
claim
