### ISSUE TITLE
Use correct logo in About dialog.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#56]
Some previous images have been  moved to assets folder(See #51). This will break the about dialog since it reference images which have been moved. Currently there is only one single logo in the resources folder. Use that logo in the about dialog. Also add some spaces between images and text and buttons.

Optional:- You can change the design and you may even get extra points for this issue if the design is very good.

**Comment by saloni33** [comment]
claim

**Comment by batflarrow** [comment]
Claim

**Comment by GhostFoxSledgehammer** [comment]
Points for this issue have been increased. See #62.

**Comment by GhostFoxSledgehammer** [comment]
Points have been decreased again. See #62.
