### ISSUE TITLE
Create a interface Image Viewer

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#59]
You need to create a interface for Image Viewer. Define all methods you think are necessary for a Image Viewer to implement.

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> Claim

Assigned to @bipulkmr-crypto

**Comment by bipulkmr-crypto** [comment]
> You need to create a interface for Image Viewer. Define all methods you think are necessary for a Image Viewer to implement.

could you tell some possible methods for the interface

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> > You need to create a interface for Image Viewer. Define all methods you think are necessary for a Image Viewer to implement.
> 
> could you tell some possible methods for the interface

setImage, disable/enable zooming/panning.

**Comment by GhostFoxSledgehammer** [comment]
Fixed in #64
