### ISSUE TITLE
Create and Implement Listener for Modes

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#69]
You need to create a mode listener interface which updates itself when the mode is changed.

You need to create class which stores the mode in which the image is being projected. It should have a public method to register a listener. 
It should have a public method to set the current mode with mode enum as argument. It should then notify all the registered listener for mode change. enums for mode can be found in `Mode` class.

See Observer Design Principle.

**Comment by GhostFoxSledgehammer** [comment]
Assigned to @Tanushree-coder

**Comment by rohanbabbar04** [comment]
claim

**Comment by GhostFoxSledgehammer** [comment]
We're past the designated time, how much more time will you need?

**Comment by Tanushree-coder** [comment]
> > > @Tanushree-coder We're past the designated time, how much more time will you need?
> > 
> > 
> > sir, can I get time till evening?
> 
> Ok complete your PR by 7:00 PM today.

sure sir, thank you!
