### ISSUE TITLE
Setup Project to claim new Issues.

### ISSUE THREAD

**Issue by GhostFoxSledgehammer** [opencodeiiita/PanoViewer#9]
Edit:-Checkout `issue-9` branch for this issue.
You need to complete this issue in order to become eligible to work on other issues.

You need to reply with screenshots of running gradle build for this project and also run the generated jar file present in `/build/libs` after running the build. Instructions for running the jar file is in `README.md`.

Since no PRs will be created, points for this will be added manually(I will notify you when that happens), probably at the end of OpenCode'21.

Eligible Participants(This means below mentioned people have completed the issue and are now eligible to claim other issues):-
- @rohanbabbar04 :heavy_check_mark:
- @medhatiwari :heavy_check_mark:
- @gaurav1058 :heavy_check_mark:
- @isharawat :heavy_check_mark:
- @bipulkmr-crypto  :heavy_check_mark:
- @jalanprakhar :heavy_check_mark:
- @batflarrow :heavy_check_mark:
- @krypton001 :heavy_check_mark:
- @shadaanhussain :heavy_check_mark:
- @Tanushree-coder :heavy_check_mark:
- @Puja-Saraf :heavy_check_mark:
- @Ms-Error :heavy_check_mark:
- @Pratik-Sarkate :heavy_check_mark:
- @raghavgoel25 :heavy_check_mark:
- @diyawaghmare :heavy_check_mark:
- @karankc23 :heavy_check_mark:
- @adtoria :heavy_check_mark:
- @Aneesh02 :heavy_check_mark:
- @AgrimVerma :heavy_check_mark:
- @KIRTEE-TECH :heavy_check_mark:
- @aayoushee01 :heavy_check_mark:
- @rahulsingh-20 :heavy_check_mark:
- @shashwat-mittal :heavy_check_mark:

**Comment by GhostFoxSledgehammer** [comment]
Example :-
![image](https://user-images.githubusercontent.com/54080100/135895495-be80f0ae-8c18-4458-832b-a79d95e4f403.png)

![image](https://user-images.githubusercontent.com/54080100/135895715-fe55c674-49cb-4015-8894-efc026bf7bac.png)

You can use any image to run the jar file.

**Comment by rohanbabbar04** [comment]
![image](https://user-images.githubusercontent.com/77425744/135897963-8cc5cd29-8d44-4d8a-ab28-18de60311847.png)

Above is the build(Windows)

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by rohanbabbar04** [comment]
> > ![image](https://user-images.githubusercontent.com/77425744/135897963-8cc5cd29-8d44-4d8a-ab28-18de60311847.png)
> > Above is the build(Windows)
> 
> Also paste the running jar file like in the example above. Edit your previous comment don't create a new one.

Done

**Comment by medhatiwari** [comment]
- Project Setup

<img width="935" alt="1" src="https://user-images.githubusercontent.com/75640645/135950755-d2afb8e3-a4a7-4e5f-8266-5e913ab63289.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/75640645/135950794-3568a98a-5561-4814-95e0-2ed0d14720dc.png">

**Comment by gaurav1058** [comment]
## Project Setup :sleepy:  :-

![Screenshot from 2021-10-05 11-27-55](https://user-images.githubusercontent.com/76611425/135968554-ad86702a-9274-4e74-97bc-8b5119b37d8b.png)

Is this the correct way, will i move forward to contribute in this project? :astronaut:

**Comment by isharawat** [comment]
**Project Setup:**
![Screenshot (97)](https://user-images.githubusercontent.com/76896205/136052638-45f4c669-3a77-4bd4-88b8-90000b4b46c0.png)
![Screenshot (98)](https://user-images.githubusercontent.com/76896205/136052655-642c2957-428c-40ea-b55c-a3d2f1143446.png)

:

**Comment by bipulkmr-crypto** [comment]
Build Success
![Screenshot from 2021-10-06 09-39-12](https://user-images.githubusercontent.com/72005385/136140712-7eea6397-9606-4f54-b925-667c12f71555.png)
Jar file running successfully
![Screenshot from 2021-10-06 09-55-08](https://user-images.githubusercontent.com/72005385/136140739-ccf02fc7-1b54-4199-b118-d75cfb9116a6.png)

**Comment by jalanprakhar** [comment]
> You need to complete this issue before you can work on other issues.
> 
> You need to reply with screenshots of running gradle build for this project and also run the generated jar file present in `/build/libs` after running the build. Instructions for running the jar file is in `README.md`.
> 
> Since no PRs will be created, points for this will be added manually(I will notify you when that happens), probably at the end of OpenCode'21.
> 
> Eligible Participants:-
> 
> * @rohanbabbar04
> * @medhatiwari
> * @gaurav1058
> * @isharawat
> * @bipulkmr-crypto

![image](https://user-images.githubusercontent.com/75791114/136141665-fd1f640e-91d4-4f06-89bf-48ea11f23549.png)

**Comment by batflarrow** [comment]
Project Setup: 
![image](https://user-images.githubusercontent.com/56157504/136142473-e45f1dc6-56e7-4647-b069-ab11f10cba6a.png)
![image](https://user-images.githubusercontent.com/56157504/136142528-90351f68-ef6b-45fc-9a10-a3fdf2fa122c.png)

**Comment by Tanushree-coder** [comment]
> You need to complete this issue before you can work on other issues.
> 
> You need to reply with screenshots of running gradle build for this project and also run the generated jar file present in `/build/libs` after running the build. Instructions for running the jar file is in `README.md`.
> 
> Since no PRs will be created, points for this will be added manually(I will notify you when that happens), probably at the end of OpenCode'21.
> 
> Eligible Participants:-
> 
> * @rohanbabbar04
> * @medhatiwari
> * @gaurav1058
> * @isharawat
> * @bipulkmr-crypto
> * @jalanprakhar
> * @batflarrow
> * @krypton001

Project set-up : 

![image](https://user-images.githubusercontent.com/75807670/136181859-655f6a1b-348f-4347-80dd-3eea3fad3269.png)

**Comment by Pratik-Sarkate** [comment]
Project Setup:
![image](https://user-images.githubusercontent.com/74398075/136332058-00e54d67-3121-4c4d-b310-494e75450e7f.png)
![image](https://user-images.githubusercontent.com/74398075/136332270-35dca670-26b4-49f2-8433-c77c28524f81.png)

**Comment by diyawaghmare** [comment]
Project setup done.

![diyawaghmare](https://user-images.githubusercontent.com/56413380/136563460-a52afc21-8047-449e-bc4b-c3192fc2c779.png)

**Comment by adtoria** [comment]
- Project Setup Done.

![Screenshot (128)](https://user-images.githubusercontent.com/87179624/136644583-ae080d5b-9d78-4cc3-a655-aa5d860746a4.png)

![Screenshot (129)](https://user-images.githubusercontent.com/87179624/136644585-d07c56e4-2aea-46b2-a28e-10d3b641611d.png)

**Comment by KIRTEE-TECH** [comment]
-  project setup done
![Screenshot (84)](https://user-images.githubusercontent.com/76700116/137278174-a7a8a616-8a45-40e3-aee8-2992580ae63d.png)

**Comment by aayoushee01** [comment]
-Project setup done
![2021-10-15 (6)](https://user-images.githubusercontent.com/75840618/137398950-1a7d3cb4-db71-4d89-bba9-3057f3418281.png)

**Comment by GhostFoxSledgehammer** [comment]
I've added all your points, if not updated then let me know.
